# Generated by Django 3.0.8 on 2020-08-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_answer_time',
            field=models.DateTimeField(null=True),
        ),
    ]
