# Generated by Django 3.0.4 on 2020-12-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20201218_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='Score',
            field=models.IntegerField(null=True),
        ),
    ]
