# Generated by Django 3.0.4 on 2020-12-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20201218_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='Score',
            field=models.IntegerField(default=0),
        ),
    ]
