# Generated by Django 3.0.4 on 2021-02-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_scorer_condition_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorer',
            name='condition_number',
        ),
        migrations.AlterField(
            model_name='scorer',
            name='score',
            field=models.IntegerField(default=None),
        ),
    ]
